# File generated by kdevelop's qmake manager.
# -------------------------------------------
# Subdir relative project main directory: .
# Target is a subdirs project

SUBDIRS += interfaces \
           src \
           plugins
TEMPLATE = subdirs
