#############################################################################
# Makefile for building: qoctopus
# Generated by qmake (1.07a) (Qt 3.3.4) on: Sat Mar  5 15:24:16 2005
# Project:  qoctopus.pro
# Template: subdirs
# Command: $(QMAKE) -o Makefile qoctopus.pro
#############################################################################

MAKEFILE =	Makefile
QMAKE    =	qmake
DEL_FILE =    rm -f
CHK_DIR_EXISTS= test -d
MKDIR    = mkdir -p
INSTALL_FILE= 
INSTALL_DIR = 
SUBTARGETS =	 \
		sub-interfaces \
		sub-src \
		sub-plugins

first: all

all: Makefile $(SUBTARGETS)

interfaces/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) "interfaces" || $(MKDIR) "interfaces"
	cd interfaces && $(QMAKE) interfaces.pro -o $(MAKEFILE)
sub-interfaces: interfaces/$(MAKEFILE) FORCE
	cd interfaces && $(MAKE) -f $(MAKEFILE)

src/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) "src" || $(MKDIR) "src"
	cd src && $(QMAKE) src.pro -o $(MAKEFILE)
sub-src: src/$(MAKEFILE) FORCE
	cd src && $(MAKE) -f $(MAKEFILE)

plugins/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) "plugins" || $(MKDIR) "plugins"
	cd plugins && $(QMAKE) plugins.pro -o $(MAKEFILE)
sub-plugins: plugins/$(MAKEFILE) FORCE
	cd plugins && $(MAKE) -f $(MAKEFILE)

Makefile: qoctopus.pro  /usr/lib/qt3/mkspecs/linux-g++/qmake.conf 
	$(QMAKE) -o Makefile qoctopus.pro
qmake: qmake_all
	@$(QMAKE) -o Makefile qoctopus.pro

all: $(SUBTARGETS)
qmake_all: interfaces/$(MAKEFILE) src/$(MAKEFILE) plugins/$(MAKEFILE)
	 ( [ -d interfaces ] && cd interfaces ; grep "^qmake_all:" $(MAKEFILE) && $(MAKE) -f $(MAKEFILE) qmake_all; ) || true
	 ( [ -d src ] && cd src ; grep "^qmake_all:" $(MAKEFILE) && $(MAKE) -f $(MAKEFILE) qmake_all; ) || true
	 ( [ -d plugins ] && cd plugins ; grep "^qmake_all:" $(MAKEFILE) && $(MAKE) -f $(MAKEFILE) qmake_all; ) || true
clean uicables mocables uiclean mocclean lexclean yaccclean : qmake_all FORCE
	 ( [ -d interfaces ] && cd interfaces ; $(MAKE) -f $(MAKEFILE) $@; ) || true
	 ( [ -d src ] && cd src ; $(MAKE) -f $(MAKEFILE) $@; ) || true
	 ( [ -d plugins ] && cd plugins ; $(MAKE) -f $(MAKEFILE) $@; ) || true
uninstall_subdirs: qmake_all FORCE
	 ( [ -d interfaces ] && cd interfaces ; $(MAKE) -f $(MAKEFILE) uninstall; ) || true
	 ( [ -d src ] && cd src ; $(MAKE) -f $(MAKEFILE) uninstall; ) || true
	 ( [ -d plugins ] && cd plugins ; $(MAKE) -f $(MAKEFILE) uninstall; ) || true
install_subdirs: qmake_all FORCE
	 ( [ -d interfaces ] && cd interfaces ; $(MAKE) -f $(MAKEFILE) install; ) || true
	 ( [ -d src ] && cd src ; $(MAKE) -f $(MAKEFILE) install; ) || true
	 ( [ -d plugins ] && cd plugins ; $(MAKE) -f $(MAKEFILE) install; ) || true
distclean: qmake_all FORCE
	 ( [ -d interfaces ] && cd interfaces ; $(MAKE) -f $(MAKEFILE) $@; $(DEL_FILE) $(MAKEFILE); ) || true
	 ( [ -d src ] && cd src ; $(MAKE) -f $(MAKEFILE) $@; $(DEL_FILE) $(MAKEFILE); ) || true
	 ( [ -d plugins ] && cd plugins ; $(MAKE) -f $(MAKEFILE) $@; $(DEL_FILE) $(MAKEFILE); ) || true

install:  install_subdirs

uninstall:  uninstall_subdirs

FORCE:

