# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./plugins
# Target is a subdirs project 

SUBDIRS += connect \
           default \
           tell \
           db \
           wall \
           help \
           msg \
           prepost \
           pangee \
           log \
           vote 
TEMPLATE = subdirs 
CONFIG += release \
          warn_on \
          qt \
          thread 
