# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./plugins/log
# Target is a library:  ../../interfaces/libinterfaces.a

SOURCES += log.cpp 
HEADERS += log.h 
TEMPLATE = lib 
CONFIG += release \
          warn_on \
          qt \
          thread \
          plugin 
DESTDIR = ../../datas/plugins 
QMAKE_LIBDIR = ../../interfaces 
OBJECTS_DIR = .obj 
MOC_DIR = .moc 
INCLUDEPATH = ../../interfaces 
LIBS += ../../interfaces/libinterfaces.a 
