# File generated by kdevelop's qmake manager.
# -------------------------------------------
# Subdir relative project main directory: ./plugins/db
# Target is a library:

SOURCES += db.cpp \
           domutil.cpp
HEADERS += db.h \
           domutil.h
TEMPLATE = lib
CONFIG += release \
          warn_on \
          qt \
          thread \
          plugin
DESTDIR = ../../datas/plugins/
QMAKE_LFLAGS_DEBUG = -lcrypt
QMAKE_LFLAGS_RELEASE = -lcrypt
OBJECTS_DIR = .obj
MOC_DIR = .moc
INCLUDEPATH = ../../interfaces
LIBS += ../../interfaces/libinterfaces.a
TARGETDEPS += ../../interfaces/libinterfaces.a

QT += xml
QT -= gui

debug {
	DEFINES += OCT_DEBUG
}
