# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./interfaces
# Target is a library:  

HEADERS += ConnectionPlugin.h \
           DatabasePlugin.h \
           Plugin.h \
           PluginManagerInterface.h \
           DefaultPlugin.h \
           PrePostPlugin.h \
           LogPlugin.h \
           plugins.h \
           ExtendedPlugin.h 
TEMPLATE = lib 
CONFIG += release \
          warn_on \
          qt \
          thread \
          staticlib 
QMAKE_CXXFLAGS_DEBUG += -g3 \
                        -Wall \
                        -Werror \
                        -Wno-long-long \
                        -ansi \
                        -pedantic 
QMAKE_CXXFLAGS_RELEASE += -Wall \
                          -Werror \
                          -Wno-long-long \
                          -ansi \
                          -pedantic 
OBJECTS_DIR = .obj 
MOC_DIR = .moc 
