# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: .
# Target is a subdirs project 

SUBDIRS += interfaces \
           src \
           plugins 
TEMPLATE = subdirs 
CONFIG += release \
          warn_on 
QMAKE_CXXFLAGS_DEBUG += -Wall \
                        -Werror \
                        -Wno-long-long \
                        -ansi \
                        -pedantic 
QMAKE_CXXFLAGS_RELEASE += -Wall \
                          -Werror \
                          -Wno-long-long \
                          -ansi \
                          -pedantic 
