# File generated by kdevelop's qmake manager.
# -------------------------------------------
# Subdir relative project main directory: ./plugins/connect
# Target is a library:

SOURCES += connection.cpp \
	   serversocket.cpp \
	   clientsocket.cpp
HEADERS += connection.h \
	   serversocket.h \
	   clientsocket.h
TEMPLATE = lib
CONFIG += release \
          warn_on \
          qt \
          thread \
          plugin
DESTDIR = ../../datas/plugins/
OBJECTS_DIR = .obj
MOC_DIR = .moc
INCLUDEPATH = ../../interfaces
LIBS += ../../interfaces/libinterfaces.a
TARGETDEPS += ../../interfaces/libinterfaces.a

QT -= gui
QT += network

debug {
	DEFINES += OCT_DEBUG
}
